#!/bin/bash

echo "Generating result.html..."

cat <<EOF > result.html
<html>
  <head><title>GitHub Actions Demo</title></head>
  <body>
    <h1>Hello, Kannan! 🎉</h1>
    <p>This is a report generated by GitHub Actions on $(date).</p>
  </body>
</html>
EOF

echo "result.html generated!"
