name: Hello Workflow

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run main script
        run: bash main.sh

      - name: Upload HTML file
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: result.html

